apiVersion: v1
kind: Service
metadata:
  name: helloworld
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "hello-task"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
  labels:
    app: helloworld
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld

spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: mustafaeid/test:test
          ports:
            - containerPort: 8080


