apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld

spec:
  replicas: 4
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: mustafaeid/test:"${{env.VERSION}}"
          ports:
            - containerPort: 80


